# Generated by Django 5.2.5 on 2025-09-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
